### ISSUE TITLE
Bug: region selection incorrect on Wayland with scaling

### ISSUE THREAD

**Issue by davisrichard437** [thenaterhood/gscreenshot#195]
## Summary

I am having trouble using gscreenshot's region capture on Wayland. I am using [sway](https://swaywm.org/) with fractional scaling (1.5x). When I attempt to take a screenshot via a region selection, the resulting image is of a smaller region than I selected, with corners up and to the left of the selected region.

## gscreenshot examples

For example, here is a screenshot of the entire screen (no region selection):

![image](https://github.com/thenaterhood/gscreenshot/assets/85075437/be10ac21-9572-47c6-9116-60d2b32cb07e)

And here is a screenshot where I have used selected the entire screen as a region:

![image](https://github.com/thenaterhood/gscreenshot/assets/85075437/23d33634-950d-4d09-8849-2f7f44632db0)

I do not have this problem when sway is unscaled (`swaymsg output eDP-1 scale 1.0` or similar). Here is a screenshot using a region selection of the whole screen with 1.0 scaling:

![image](https://github.com/thenaterhood/gscreenshot/assets/85075437/e6f8a7ad-4b4f-4017-916c-cade82bed6c6)

The problem persists with 2.0 scaling, so it is not an issue of fractional or whole-number scaling. Here is a screenshot using region selection of the whole screen with 2.0 scaling:

![image](https://github.com/thenaterhood/gscreenshot/assets/85075437/34d0a1ba-c794-4901-8527-fcfb691af03d)

This screenshot is (visually) exactly half the screen, so I imagine the program somehow misinterprets scaled coordinates.

## grim/slurp examples

I do not have this same problem with "raw" grim/slurp region selection (`grim -g "$(slurp)"`).

No region selection: 

![image](https://github.com/thenaterhood/gscreenshot/assets/85075437/c72f4d4e-3028-47fe-8d77-b6213c50c9d9)

Region selection of the entire screen:

![image](https://github.com/thenaterhood/gscreenshot/assets/85075437/7195b293-d56a-4a65-971d-a94111269f38)

## Some information

- OS: NixOS Unstable 24.11.20240613.e9ee548 (Vicuna)
- WM: sway 1.9
- `gscreenshot --version`

```
Using grim screenshot backend
gscreenshot 3.5.1; A simple screenshot tool supporting multiple backends.
Available features: Cursor Capture (gscreenshot), Full Screen Capture (grim), Alternate Cursor (gscreenshot), Region Selection (slurp), Reuse Region (slurp)
https://github.com/thenaterhood/gscreenshot
...
```

- Package: [mine](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/gscreenshot/default.nix) for NixOS/nixpkgs. There's a chance I have it packaged wrong, so I'd be interested to know if others can reproduce this error.

**Comment by thenaterhood** [comment]
That's very interesting! For context about how gscreenshot does region selection, it takes a screenshot of the entire display then crops it based on the output of the region selection tool, in your case slurp. It's possible that gscreenshot needs to adjust something by the scaling ratio.

**Comment by thenaterhood** [comment]
Reproducible in KDE

**Comment by thenaterhood** [comment]
This should be working in gscreenshot 3.6.1

**Comment by davisrichard437** [comment]
I'm afraid it still doesn't work for me, but I'll do some more digging

**Comment by thenaterhood** [comment]
Try out version 3.6.2 which I just released this morning and see if it works any better. One of the Gtk calls was wrong and gscreenshot was falling back to another method of getting the scaling that might not have been accurate on your setup.

**Comment by davisrichard437** [comment]
Unfortunately no, now I get something like this:

![image](https://github.com/user-attachments/assets/48afa287-477c-4e16-9979-f6da30ca89b9)

It seems to be larger (dilated down and to the right) than the region selection I had chosen, even going off the screen. For comparison, with grim/slurp:

![image](https://github.com/user-attachments/assets/aefa50e9-8f5a-42f6-b0cc-91a8590ba570)

One thing to consider is that I am currently using two monitors with different scaling; this could potentially be a problem in detecting scaling. One is a 1920x1080 external display with no scaling and the other is a 2256x1504 laptop screen with 1.5 scaling. However, even when I disconnect the external display, the problem persists, so I doubt this is the cause of the issue.

If it would help, I'd be happy to run a version with debugging/print statements and send the output here.

**Comment by thenaterhood** [comment]
Here's a Python script you can run which should output the scaling factor of the current screen. It will call into gscreenshot's functions as well as another call that uses a different approach.

```
from gscreenshot.scaling.scaling_factor import (
    get_scaling_from_gdk,
    get_scaling_from_qt,
    get_scaling_from_xft_dpi,
)

def another_method_getting_scaling_from_gdk():
    """Get scaling factor from Gtk"""
    # pylint: disable=import-outside-toplevel
    import gi
    gi.require_version('Gtk', '3.0')
    from gi.repository import Gtk # type: ignore

    w = Gtk.Window()
    screen = w.get_screen()
    display = screen.get_display()
    monitor = (
        display.get_monitor_at_window(screen.get_root_window())
        or display.get_primary_monitor()
        or display.get_monitor(0)
    )
    if monitor:
        return monitor.get_scale_factor()
    return None

for scaling_detector in (
    get_scaling_from_gdk,
    another_method_getting_scaling_from_gdk,
    get_scaling_from_qt,
    get_scaling_from_xft_dpi,
):
    print(f"{scaling_detector} says scale is {scaling_detector()}")
```

**Comment by thenaterhood** [comment]
Fantastic, thank you! That's a really good datapoint. Interesting variation between those with only one of them actually having the correct value for your setup.

**Comment by Momo8289** [comment]
This appears to be fixed for me in the latest version, 3.8.0-1

**Comment by thenaterhood** [comment]
Thanks @Momo8289! I did slip some scaling improvements into 3.8.0 :). Glad to hear it helped someone.

While I think it's better "in general," on my own setup I still have some misalignment of selections so there's still room for improvement.
